### ISSUE TITLE
刚一运行就ERROR满天飞,请问哪里可以临时去掉对mongodb和redis的依赖

### ISSUE THREAD

**Issue by RussiaVk** [CreditTone/regchecker#1]
`Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-05-10 19:07:10.053 ERROR 8028 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.mongodb.MongoClientURI.getOptions(MongoClientURI.java:353)

The following method did not exist:

    com.mongodb.ConnectionString.getRetryWritesValue()Ljava/lang/Boolean;

The method's class, com.mongodb.ConnectionString, is available from the following locations:

    jar:file:/C:/Users/Admin/.m2/repository/org/mongodb/mongodb-driver-core/3.8.2/mongodb-driver-core-3.8.2.jar!/com/mongodb/ConnectionString.class

It was loaded from the following location:

    file:/C:/Users/Admin/.m2/repository/org/mongodb/mongodb-driver-core/3.8.2/mongodb-driver-core-3.8.2.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of com.mongodb.ConnectionString

java.io.IOException: Cannot run program "ps": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.deep007.goniub.killer.LinuxKiller.executePsCommand(LinuxKiller.java:62)
	at com.deep007.goniub.killer.LinuxKiller.executePsCommand(LinuxKiller.java:98)
	at com.deep007.goniub.killer.LinuxKiller.getChildLinuxProcess(LinuxKiller.java:128)
	at com.deep007.goniub.killer.LinuxJvmProcrssMonitor$LinuxJvmProcrssMonitorTask.run(LinuxJvmProcrssMonitor.java:80)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more
java.io.IOException: Cannot run program "ps": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.deep007.goniub.killer.LinuxKiller.executePsCommand(LinuxKiller.java:62)
	at com.deep007.goniub.killer.LinuxKiller.executePsCommand(LinuxKiller.java:98)
	at com.deep007.goniub.killer.LinuxKiller.getChildLinuxProcess(LinuxKiller.java:128)
	at com.deep007.goniub.killer.LinuxJvmProcrssMonitor$LinuxJvmProcrssMonitorTask.run(LinuxJvmProcrssMonitor.java:80)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more
java.io.IOException: Cannot run program "ps": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.deep007.goniub.killer.LinuxKiller.executePsCommand(LinuxKiller.java:62)
	at com.deep007.goniub.killer.LinuxKiller.executePsCommand(LinuxKiller.java:98)
	at com.deep007.goniub.killer.LinuxKiller.getChildLinuxProcess(LinuxKiller.java:128)
	at com.deep007.goniub.killer.LinuxJvmProcrssMonitor$LinuxJvmProcrssMonitorTask.run(LinuxJvmProcrssMonitor.java:80)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more`

**Comment by CreditTone** [comment]
pom.xml goniub 更新到1.8.3可以减少一部分的error。但是依然运行不了，**说了不维护了**。跑肯定跑不起来。只是分享出来让大家了解下400+网站的撞库核心代码。

**Comment by CreditTone** [comment]
把爬虫部分代码拷贝下，其他部分可以自己定制。不需要用我的，是不是京东老弟
